leftnav:
- identifier: c9bdcc40-1647-d3ef-0604-1a20664d8db8
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 959ceb12-6fc6-fd8e-e389-6f2eb4276ad2
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: 3e0a18cf-ccc9-a8fe-1d0f-56282db1a7c1
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: 0affbb8a-ec46-6278-bebf-ba8a736c1023
  name: Assignments
  pageRef: /pages/assignments
  weight: 40
- identifier: c5195186-2139-4d3a-6192-f8266bba123e
  name: Projects
  pageRef: /pages/projects
  weight: 50
